name: opmlparser
version: 0.1.0
description: A dart package for parsing OPML. All features of the official spec is included.
homepage: https://github.com/abhinavmarwaha/opmlparser
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  xml: "^4.2.0"
  intl: "^0.16.1"
dev_dependencies:
  test: ^1.3.0
  http: ^0.12.2
